/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaEveryday.app;

import javaEveryday.list.LinkedList;

import static javaEveryday.utilities.StringUtils.join;
import static javaEveryday.utilities.StringUtils.split;
import static javaEveryday.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import java.util.List;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        List<String> list = new java.util.LinkedList<>();
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
